In [50]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [51]:
df = pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [52]:
df.shape

(1599, 12)

In [53]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [54]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [55]:
df['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [56]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(1599, 11)
(1599,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [57]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [58]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.30)    
print(x_train.shape)                                                       
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1119, 11)
(480, 11)
(1119,)
(480,)


In [61]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [62]:
def gen_metrics(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print('Confusion Matrix = \n',cm)
    print('Classification Report = \n',classification_report(ytest,ypred,zero_division=0))
    
def tt_score(model):
    print('Training Score = ', model.score(x_train,y_train))
    print('Testing Score = ', model.score(x_test,y_test))

### 1) LogisticReg

In [63]:
from sklearn.linear_model import LogisticRegression

In [64]:
m1 = LogisticRegression(max_iter=1000,solver='liblinear')
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [65]:
tt_score(m1)

Training Score =  0.5746201966041108
Testing Score =  0.59375


In [66]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[5 6 6 5 5 6 6 5 5 5 5 5 6 5 5 6 6 5 5 5 6 6 6 5 5 5 6 6 6 5 5 5 5 6 5 6 6
 6 5 5 6 5 5 6 6 6 6 5 6 6 5 5 7 5 5 5 5 5 6 5 6 5 5 6 6 6 5 6 6 5 5 6 6 5
 6 6 6 5 5 5 6 6 5 5 5 5 5 5 5 5 6 5 6 6 6 6 6 5 5 6 7 5 6 6 6 5 5 6 5 6 6
 5 6 5 5 5 5 6 5 6 5 5 5 6 6 5 6 6 6 5 5 5 5 5 5 6 5 6 5 5 5 6 5 5 6 5 6 5
 6 5 5 5 5 5 6 5 5 5 5 6 6 5 6 5 6 6 6 5 6 5 5 6 5 5 6 5 5 6 6 6 6 6 5 6 6
 5 5 6 6 6 5 5 5 6 5 5 6 5 6 5 5 6 5 6 5 5 5 5 5 6 6 6 6 5 6 6 6 6 5 5 6 5
 5 5 5 5 5 7 5 6 6 5 6 6 6 6 6 6 6 6 5 6 5 6 5 5 5 6 5 5 6 6 5 6 5 6 6 6 6
 5 6 5 6 5 5 5 5 5 6 6 5 6 5 5 6 6 6 5 5 6 7 5 6 6 5 6 5 6 5 5 5 5 6 5 5 6
 6 5 6 5 5 5 5 5 6 6 5 6 6 6 5 5 6 5 5 5 6 5 5 5 5 6 5 5 5 5 6 5 5 6 5 5 5
 5 5 5 5 6 5 6 6 6 6 5 6 6 5 5 5 5 5 5 5 5 5 6 6 6 5 6 5 5 5 5 5 6 6 6 6 6
 5 6 7 6 5 5 6 6 5 6 5 6 5 5 6 6 6 6 6 5 5 5 5 6 5 6 5 6 6 5 6 5 5 6 5 5 5
 6 6 5 5 6 5 5 6 6 5 5 5 6 6 6 6 6 5 6 6 6 6 6 6 5 5 6 5 5 5 6 5 5 6 5 5 6
 5 5 5 5 6 5 6 5 5 6 6 6 6 6 5 6 5 6 5 5 6 6 5 5 5 5 6 6 6 5 5 6 6 5 6 5]


In [67]:
gen_metrics(y_test,ypred_m1)

Confusion Matrix = 
 [[  0   0   2   0   0   0]
 [  0   0  11   2   0   0]
 [  0   0 165  30   0   0]
 [  0   0  79 119   2   0]
 [  0   0   2  62   1   0]
 [  0   0   0   3   2   0]]
Classification Report = 
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        13
           5       0.64      0.85      0.73       195
           6       0.55      0.59      0.57       200
           7       0.20      0.02      0.03        65
           8       0.00      0.00      0.00         5

    accuracy                           0.59       480
   macro avg       0.23      0.24      0.22       480
weighted avg       0.52      0.59      0.54       480



### 2) Decision Tree

In [68]:
from sklearn.tree import DecisionTreeClassifier

In [69]:
m2 = DecisionTreeClassifier(criterion='entropy',max_depth=15)
m2.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=15)

In [70]:
tt_score(m2)

Training Score =  0.9991063449508489
Testing Score =  0.6125


In [71]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[5 7 6 5 6 6 7 5 5 6 5 5 7 7 5 6 6 6 5 5 7 6 6 5 5 5 6 7 8 6 5 6 5 7 6 6 6
 6 6 5 7 3 5 6 6 7 6 4 6 5 5 5 6 5 6 5 5 5 6 7 7 4 5 6 5 7 5 7 5 5 5 6 6 4
 5 7 6 5 5 5 7 5 6 6 5 5 6 5 5 4 6 5 5 6 6 6 6 5 5 7 6 5 7 5 6 5 6 6 6 6 7
 5 6 5 5 6 5 6 5 8 5 6 5 6 6 5 6 6 6 5 5 6 5 5 4 6 5 6 5 5 6 5 5 5 6 5 7 5
 6 6 6 4 4 5 8 5 6 6 5 7 7 4 5 5 6 7 7 5 5 6 6 6 5 5 5 5 5 7 7 7 7 7 5 6 6
 5 5 7 6 6 5 5 5 6 6 6 7 5 6 6 5 8 5 6 5 5 8 6 6 6 7 6 6 5 7 5 7 7 5 5 7 5
 5 5 5 5 5 7 6 6 6 6 5 6 5 7 8 7 6 7 5 6 6 6 6 6 5 8 6 5 7 7 5 6 5 6 6 6 4
 6 6 6 6 5 5 5 5 5 7 6 5 6 6 5 5 5 7 6 5 5 6 5 6 6 6 6 5 6 5 6 5 6 6 5 5 6
 7 5 7 4 5 5 5 5 6 4 4 6 8 5 5 5 7 3 4 5 5 6 5 4 5 6 4 6 6 6 6 6 5 6 6 5 4
 5 5 5 6 8 5 6 6 6 6 5 6 6 5 5 5 5 8 5 4 5 5 7 6 6 6 6 5 5 5 4 6 6 6 6 6 6
 5 6 7 5 5 5 6 6 5 7 7 5 5 6 6 6 5 6 6 5 6 5 5 7 5 7 5 5 6 5 6 5 6 7 6 6 6
 6 6 5 5 5 5 5 5 6 6 5 6 5 5 7 6 6 5 8 6 6 6 6 6 5 5 5 6 6 5 5 6 5 5 5 6 6
 5 5 5 5 6 5 6 6 5 6 6 6 6 6 5 8 5 6 5 5 6 5 5 5 6 6 6 6 7 5 6 6 6 7 7 5]


In [72]:
gen_metrics(y_test,ypred_m2)

Confusion Matrix = 
 [[  0   0   2   0   0   0]
 [  0   3   5   5   0   0]
 [  2  12 143  35   2   1]
 [  0   3  48 118  25   6]
 [  0   0   2  30  29   4]
 [  0   0   0   3   1   1]]
Classification Report = 
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.17      0.23      0.19        13
           5       0.71      0.73      0.72       195
           6       0.62      0.59      0.60       200
           7       0.51      0.45      0.48        65
           8       0.08      0.20      0.12         5

    accuracy                           0.61       480
   macro avg       0.35      0.37      0.35       480
weighted avg       0.62      0.61      0.62       480



### 3) KNN

In [73]:
from sklearn.neighbors import KNeighborsClassifier

In [74]:
m3 = KNeighborsClassifier(n_neighbors=25)
m3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=25)

In [75]:
tt_score(m3)

Training Score =  0.548704200178731
Testing Score =  0.5395833333333333


In [76]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[5 6 7 5 6 5 5 6 5 6 5 5 5 6 6 5 6 6 5 5 5 6 6 6 5 5 6 6 6 5 5 5 6 6 6 5 5
 6 5 5 6 5 5 5 5 6 5 5 6 5 5 5 6 5 6 5 5 5 5 5 7 5 5 6 5 6 5 6 5 5 5 6 6 6
 6 5 6 6 6 5 5 5 5 6 5 5 5 5 6 5 5 5 5 6 6 5 6 5 5 6 7 5 6 6 5 5 5 6 5 6 6
 5 5 5 5 5 5 6 5 5 5 5 5 6 6 5 5 7 6 5 5 6 5 6 6 6 5 6 5 5 6 5 5 5 6 5 6 5
 5 5 6 6 5 5 5 5 5 5 5 5 6 5 6 5 5 5 6 5 5 6 5 5 5 5 6 5 5 5 6 6 6 5 5 7 5
 6 5 6 6 5 5 5 6 6 5 5 6 5 5 5 5 6 5 5 5 5 6 5 6 6 5 6 6 5 6 5 5 6 5 6 6 5
 5 6 5 5 5 6 5 6 6 5 6 6 5 6 6 6 6 5 5 5 5 5 6 6 5 5 5 5 5 6 5 6 5 6 6 6 5
 6 5 5 6 6 5 6 5 5 6 6 6 5 5 5 5 6 5 6 5 6 7 5 6 6 5 6 5 6 5 5 6 5 6 5 5 5
 7 6 6 6 5 5 5 5 6 5 5 6 6 6 5 5 5 5 5 6 5 6 5 6 5 6 6 6 5 5 6 5 5 6 5 5 5
 5 5 5 5 6 5 5 6 6 5 6 6 5 5 5 5 5 5 5 6 5 5 6 6 5 5 6 5 5 5 5 5 5 5 5 5 5
 5 5 6 5 6 5 6 6 5 7 5 6 5 5 5 7 6 5 5 5 5 5 5 5 5 5 5 6 6 5 6 5 5 6 5 5 6
 6 6 5 5 6 5 5 5 5 6 5 6 6 6 5 6 7 5 6 5 5 5 6 6 5 5 5 5 5 5 6 5 6 6 5 6 5
 5 5 5 5 5 6 6 6 5 5 6 6 5 5 5 5 5 6 5 6 5 5 5 5 6 5 5 6 6 5 5 6 6 5 7 5]


In [77]:
gen_metrics(y_test,ypred_m3)

Confusion Matrix = 
 [[  0   0   2   0   0   0]
 [  0   0   9   3   1   0]
 [  0   0 155  40   0   0]
 [  0   0 101  97   2   0]
 [  0   0  24  34   7   0]
 [  0   0   1   3   1   0]]
Classification Report = 
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        13
           5       0.53      0.79      0.64       195
           6       0.55      0.48      0.51       200
           7       0.64      0.11      0.18        65
           8       0.00      0.00      0.00         5

    accuracy                           0.54       480
   macro avg       0.29      0.23      0.22       480
weighted avg       0.53      0.54      0.50       480



### 4) SVM

In [78]:
from sklearn.svm import SVC

In [79]:
m4 = SVC(kernel='poly',C=100,degree=4)
m4.fit(x_train,y_train)

SVC(C=100, degree=4, kernel='poly')

In [80]:
tt_score(m4)

Training Score =  0.5549597855227882
Testing Score =  0.5875


In [81]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[5 5 5 5 6 6 6 6 5 6 5 5 6 6 6 6 6 5 5 5 6 6 6 5 6 5 6 6 6 5 5 5 5 6 6 6 6
 6 5 5 5 6 5 5 5 6 5 5 6 6 5 5 6 5 5 5 5 5 6 6 6 5 5 6 6 6 5 6 6 6 5 6 6 5
 5 6 6 5 6 5 6 6 5 6 6 6 5 5 6 5 5 5 6 6 6 6 6 5 5 6 6 5 6 6 6 5 5 5 6 6 6
 5 6 5 5 5 5 6 5 6 5 5 5 6 6 5 6 6 6 5 5 6 5 5 5 6 5 6 5 5 6 6 5 5 6 5 6 5
 5 5 6 6 5 5 7 5 5 5 5 6 6 5 5 5 6 6 6 5 6 5 5 6 5 5 6 5 5 6 6 6 5 6 5 5 6
 5 5 6 6 6 5 5 6 5 6 5 6 6 5 6 5 6 5 6 5 5 6 6 6 6 6 5 6 5 6 5 6 6 5 5 6 5
 5 6 6 5 5 6 5 5 5 5 6 6 5 6 6 6 6 6 5 5 5 6 5 6 5 6 6 5 6 6 5 6 5 6 6 5 5
 5 6 5 6 5 5 5 5 5 6 6 6 6 5 5 5 5 6 6 6 6 6 5 6 6 5 6 5 6 5 5 5 6 6 5 5 6
 6 6 6 6 5 5 5 6 6 5 6 5 6 6 5 5 6 5 6 6 6 6 5 6 5 6 6 6 5 5 6 5 5 6 6 5 5
 5 5 5 6 6 5 5 6 6 6 5 6 5 5 5 5 5 6 5 5 5 6 6 6 6 5 6 5 5 5 5 5 6 7 6 6 6
 5 6 6 5 5 5 6 5 5 5 6 6 5 5 5 6 6 6 6 5 5 5 5 6 5 6 5 6 6 5 6 5 5 6 5 6 6
 6 6 5 5 6 5 5 5 6 5 5 5 6 6 6 6 6 5 6 5 6 6 6 6 5 5 7 5 5 5 6 6 5 6 5 5 6
 5 5 5 5 5 6 6 6 5 5 5 6 6 5 5 7 5 6 6 5 6 5 5 5 5 5 6 6 6 5 5 6 6 5 5 5]


In [82]:
gen_metrics(y_test,ypred_m4)

Confusion Matrix = 
 [[  0   0   2   0   0   0]
 [  0   0  11   2   0   0]
 [  0   0 149  45   1   0]
 [  0   0  69 131   0   0]
 [  0   0  13  50   2   0]
 [  0   0   0   4   1   0]]
Classification Report = 
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        13
           5       0.61      0.76      0.68       195
           6       0.56      0.66      0.61       200
           7       0.50      0.03      0.06        65
           8       0.00      0.00      0.00         5

    accuracy                           0.59       480
   macro avg       0.28      0.24      0.22       480
weighted avg       0.55      0.59      0.54       480



### 5) RandomForestClassifier

In [83]:
from sklearn.ensemble import RandomForestClassifier

In [84]:
m5 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=9)
m5.fit(x_train,y_train)

RandomForestClassifier(max_depth=9, n_estimators=80)

In [85]:
tt_score(m5)

Training Score =  0.9133154602323503
Testing Score =  0.7041666666666667


In [86]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[6 6 6 5 5 6 7 5 5 6 5 5 6 5 5 5 6 6 5 5 6 6 6 5 5 5 6 6 6 6 5 5 5 7 6 5 6
 6 5 5 7 6 5 6 6 7 6 5 6 6 5 5 6 5 5 5 5 5 6 7 6 6 5 6 6 6 5 7 6 5 5 6 6 5
 5 7 6 5 5 5 7 5 5 5 6 5 5 5 5 5 6 5 5 6 6 6 5 5 5 7 7 5 7 5 6 5 6 6 6 6 7
 5 5 5 5 5 5 6 5 6 5 6 5 6 6 5 6 6 6 5 5 5 5 5 6 6 5 6 5 5 6 5 5 5 6 5 6 5
 6 5 5 5 5 5 7 5 6 5 5 7 6 5 5 5 6 7 7 5 6 5 5 6 5 5 6 6 5 6 6 7 7 6 5 6 6
 5 5 6 6 6 5 5 5 6 5 5 6 5 6 5 5 6 5 7 5 5 6 6 6 6 7 6 6 5 7 6 7 6 5 5 7 5
 5 5 5 6 5 7 5 6 6 5 6 6 6 6 6 7 6 6 5 6 5 6 6 5 5 6 6 5 6 7 5 6 5 6 6 6 6
 5 6 5 6 5 5 5 5 5 7 6 5 6 6 5 5 5 6 5 5 6 6 5 6 6 6 5 5 6 5 5 5 6 6 5 5 6
 6 5 6 5 5 5 5 5 6 6 5 6 6 5 5 5 6 5 5 5 5 6 5 4 5 6 5 5 5 6 6 5 5 6 6 5 5
 5 5 5 5 6 5 5 6 6 6 5 6 6 5 6 5 5 5 5 6 5 5 7 6 6 5 6 5 5 5 5 5 7 7 6 6 6
 5 6 7 5 5 5 6 5 5 7 5 6 5 5 6 7 6 6 6 5 6 5 5 6 5 7 5 5 6 5 6 5 6 7 6 6 6
 6 6 5 5 5 5 5 6 6 6 5 5 6 5 7 6 6 5 7 6 6 6 6 6 5 5 5 6 5 5 6 5 5 5 5 5 6
 5 5 5 5 6 5 6 6 5 6 6 7 6 6 5 6 5 6 6 5 6 6 5 5 6 6 6 6 6 5 5 6 6 5 7 5]


In [87]:
from collections import Counter
c1 = Counter(ypred_m5)
print(c1)

Counter({5: 240, 6: 200, 7: 39, 4: 1})


In [88]:
gen_metrics(y_test,ypred_m5)

Confusion Matrix = 
 [[  0   0   2   0   0   0]
 [  0   0  10   3   0   0]
 [  0   0 175  20   0   0]
 [  0   1  51 137  11   0]
 [  0   0   2  37  26   0]
 [  0   0   0   3   2   0]]
Classification Report = 
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        13
           5       0.73      0.90      0.80       195
           6       0.69      0.69      0.69       200
           7       0.67      0.40      0.50        65
           8       0.00      0.00      0.00         5

    accuracy                           0.70       480
   macro avg       0.35      0.33      0.33       480
weighted avg       0.67      0.70      0.68       480



### Thus, RandomForestClassifier is the best model for classifying wine quality because it has the highest accuracy compared to other models.





<br>
<br>



# Let's create a function to handle any model

<br>



In [93]:
def model_perf(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    ypred = model.predict(x_test)
    print(ypred)
    cm = confusion_matrix(y_test,ypred)
    print('Confusion Matrix = \n',cm)
    print('Classification Report = \n',classification_report(y_test,ypred,zero_division=0))
    print('Accuracy Score = ',accuracy_score(y_test,ypred))
    print('Training Score = ', model.score(x_train,y_train))
    print('Testing Score = ', model.score(x_test,y_test))

In [94]:
w1 = LogisticRegression(max_iter=1000,solver='liblinear')
model_perf(w1,x_train,x_test,y_train,y_test)

[5 6 6 5 5 6 6 5 5 5 5 5 6 5 5 6 6 5 5 5 6 6 6 5 5 5 6 6 6 5 5 5 5 6 5 6 6
 6 5 5 6 5 5 6 6 6 6 5 6 6 5 5 7 5 5 5 5 5 6 5 6 5 5 6 6 6 5 6 6 5 5 6 6 5
 6 6 6 5 5 5 6 6 5 5 5 5 5 5 5 5 6 5 6 6 6 6 6 5 5 6 7 5 6 6 6 5 5 6 5 6 6
 5 6 5 5 5 5 6 5 6 5 5 5 6 6 5 6 6 6 5 5 5 5 5 5 6 5 6 5 5 5 6 5 5 6 5 6 5
 6 5 5 5 5 5 6 5 5 5 5 6 6 5 6 5 6 6 6 5 6 5 5 6 5 5 6 5 5 6 6 6 6 6 5 6 6
 5 5 6 6 6 5 5 5 6 5 5 6 5 6 5 5 6 5 6 5 5 5 5 5 6 6 6 6 5 6 6 6 6 5 5 6 5
 5 5 5 5 5 7 5 6 6 5 6 6 6 6 6 6 6 6 5 6 5 6 5 5 5 6 5 5 6 6 5 6 5 6 6 6 6
 5 6 5 6 5 5 5 5 5 6 6 5 6 5 5 6 6 6 5 5 6 7 5 6 6 5 6 5 6 5 5 5 5 6 5 5 6
 6 5 6 5 5 5 5 5 6 6 5 6 6 6 5 5 6 5 5 5 6 5 5 5 5 6 5 5 5 5 6 5 5 6 5 5 5
 5 5 5 5 6 5 6 6 6 6 5 6 6 5 5 5 5 5 5 5 5 5 6 6 6 5 6 5 5 5 5 5 6 6 6 6 6
 5 6 7 6 5 5 6 6 5 6 5 6 5 5 6 6 6 6 6 5 5 5 5 6 5 6 5 6 6 5 6 5 5 6 5 5 5
 6 6 5 5 6 5 5 6 6 5 5 5 6 6 6 6 6 5 6 6 6 6 6 6 5 5 6 5 5 5 6 5 5 6 5 5 6
 5 5 5 5 6 5 6 5 5 6 6 6 6 6 5 6 5 6 5 5 6 6 5 5 5 5 6 6 6 5 5 6 6 5 6 5]
Confusion Matrix = 
 [[  0

In [95]:
w2 = DecisionTreeClassifier(criterion='gini',max_depth=9,min_samples_split=17)
model_perf(w2,x_train,x_test,y_train,y_test)

[6 7 7 5 5 6 6 6 5 6 5 5 6 5 5 6 6 6 5 5 6 6 7 5 5 5 6 6 8 5 5 6 6 7 6 5 6
 6 5 6 7 6 5 5 6 7 6 5 6 5 6 5 8 6 6 5 5 5 6 7 5 6 5 6 5 6 6 7 6 5 5 6 6 5
 5 7 6 5 5 6 7 5 6 6 5 5 6 5 5 7 6 5 6 6 6 6 6 6 5 8 7 5 3 6 6 5 6 6 5 6 7
 6 6 5 5 6 5 6 5 7 5 6 5 6 6 5 6 7 6 5 5 6 5 6 6 7 5 6 5 6 6 5 6 5 6 5 6 6
 6 6 6 5 7 5 7 5 6 6 6 6 6 5 6 5 6 7 6 5 5 5 5 6 5 5 5 6 5 6 6 7 6 6 5 7 6
 6 6 6 6 6 5 4 5 6 5 6 6 6 5 6 5 8 5 7 5 5 5 6 6 6 7 6 6 6 6 6 7 6 5 5 7 5
 6 6 5 6 6 7 5 6 6 5 6 6 6 6 6 6 6 6 5 6 6 6 6 6 5 8 5 5 6 7 5 6 5 5 6 6 5
 5 6 6 6 5 5 5 5 5 6 6 6 7 6 5 5 5 6 6 5 5 6 5 6 6 6 5 5 6 5 5 5 6 6 5 5 6
 7 6 6 5 5 6 5 5 6 5 6 6 6 5 5 6 6 5 5 6 6 6 6 5 5 6 5 5 6 7 6 5 5 6 6 5 5
 5 5 5 6 6 5 5 6 6 6 5 5 5 5 6 5 5 5 5 6 5 5 6 6 6 6 6 5 5 5 5 5 7 8 6 6 7
 6 7 6 5 5 5 6 5 5 7 5 6 5 6 6 7 6 6 5 4 5 5 5 5 5 6 6 6 5 5 6 5 6 7 6 6 5
 6 6 5 5 5 5 5 6 6 5 6 6 6 6 7 6 6 5 6 5 6 6 6 7 5 5 6 6 5 6 5 5 5 6 6 6 6
 5 5 5 5 5 5 6 6 6 7 7 6 5 7 6 7 5 6 6 5 6 5 5 5 5 7 5 6 6 4 6 6 6 5 6 5]
Confusion Matrix = 
 [[  0